### ISSUE TITLE
[1.15.2] Log Entries

### ISSUE THREAD

**Issue by realTIMematrix** [FoundSpore/DefaultAmplfiedBiomes#3]
Hi,

please fix your code. It produces warnings in the logfiles.

Issue: Your mod is looking for updates and uses a non existing link called myurl.me

- [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [dab] Starting version check at https://myurl.me/
- [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
- javax.net.ssl.SSLHandshakeException: java.security.cert.CertificateException: No subject alternative DNS name matching myurl.me found.

I'm using:

- Minecraft 1.15.2
- Forge 31.0.1
- DefaultAmplified (1.15.2)-1.3
- BiomesOPlenty-1.15.2-10.0.0.299-universal
- jei-1.15.2-6.0.0.2

BTW: Your mod is a very good addition to BoP. Try the seed -7065323162125144336 

best regards

Andreas

**Comment by realTIMematrix** [comment]
DefaultAmplified-1.15.2-1.3.1.jar produces hard crash

**Comment by FoundSpore** [comment]
really? send the latest in a paste bin
